version: '3.3'
services:

# Nginx Service
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    links: 
      - app
    volumes:
      - ./hosts/:/etc/nginx/conf.d/
      - ./www:/var/www
      - ./logs:/var/log/nginx
    working_dir: /var/www

# PHP Service
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    links:
      - db
    volumes:
      - ./www:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini


# MySQL Service
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
